"""Parameter dataclasses for the Merton jump-diffusion Monte Carlo pipeline.

Notation is consistent with the W2 derivations:

    dX_t = (r - lambda * kappa - 0.5 * sigma**2) dt + sigma dW_t + J dN_t,
    kappa = E[exp(J)-1] = exp(mu_J + 0.5 * sigma_J**2) - 1.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class MarketParams:
    """Risk-neutral Merton jump-diffusion parameters."""

    s0: float = 100.0
    strike: float = 100.0
    maturity: float = 1.0
    rate: float = 0.05
    sigma: float = 0.20
    jump_intensity: float = 1.00
    jump_mean: float = -0.10
    jump_vol: float = 0.25

    @property
    def kappa(self) -> float:
        """Expected percentage jump size, E[exp(J)-1]."""
        return math.exp(self.jump_mean + 0.5 * self.jump_vol**2) - 1.0

    @property
    def lambda_prime(self) -> float:
        """Adjusted intensity used only in the Merton analytic formula."""
        return self.jump_intensity * (1.0 + self.kappa)

    def with_overrides(self, **overrides: float) -> "MarketParams":
        """Return a copy of the parameters with selected fields replaced."""
        values = {
            "s0": self.s0,
            "strike": self.strike,
            "maturity": self.maturity,
            "rate": self.rate,
            "sigma": self.sigma,
            "jump_intensity": self.jump_intensity,
            "jump_mean": self.jump_mean,
            "jump_vol": self.jump_vol,
        }
        values.update(overrides)
        return MarketParams(**values)


@dataclass(frozen=True)
class RunConfig:
    """Configuration for the reproducible experiment pipeline."""

    paths: int = 50_000
    steps: int = 252
    seed: int = 42
    replications: int = 5
    merton_terms: int = 150
    output_dir: Path = Path("results")
    log_level: str = "INFO"


@dataclass(frozen=True)
class PriceResult:
    """Monte Carlo price estimate and standard error."""

    price: float
    standard_error: float


@dataclass(frozen=True)
class McSample:
    """Terminal prices generated by the simulation engine."""

    terminal_prices: "np.ndarray"
    control_prices: "np.ndarray | None" = None
    antithetic_half_size: int | None = None


@dataclass(frozen=True)
class SmileScenario:
    """Named parameter overrides used in the implied-volatility smile comparison."""

    label: str
    overrides: dict[str, float] = field(default_factory=dict)
