"""Monte Carlo pricing engine for the Merton jump-diffusion model (W3).

Consolidates simulation, analytic pricing, variance-reduction experiments,
convergence studies, and plot renderers into a single production module.

Theory (W2 notation)
--------------------
    dX_t = (r - lambda*kappa - 0.5*sigma^2) dt + sigma dW_t + J dN_t
    kappa = E[exp(J) - 1] = exp(mu_j + 0.5*sigma_j^2) - 1

The Merton (1976) analytic formula is a Poisson-weighted Black-Scholes sum:
    C = sum_n  Pois(n; lambda'*T) * BS(S, K, T, r_n, sigma_n)

Entry point
-----------
    from src.mc_engine import write_outputs
    write_outputs(params, run_config, path_sizes, step_sizes, strikes)
"""

from __future__ import annotations

import math
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Sequence

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.optimize import brentq
from scipy.stats import norm

from .config import MertonParams, RunConfig

LOGGER = logging.getLogger(__name__)


# ── analytic pricing ─────────────────────────────────────────────────────────

def black_scholes_call(s: float, k: float, t: float, r: float, sigma: float) -> float:
    """Return the Black-Scholes European call price."""
    if t <= 0.0:
        return max(s - k, 0.0)
    if sigma <= 0.0:
        return max(s - k * math.exp(-r * t), 0.0)
    vol_sqrt_t = sigma * math.sqrt(t)
    d1 = (math.log(s / k) + (r + 0.5 * sigma ** 2) * t) / vol_sqrt_t
    d2 = d1 - vol_sqrt_t
    return float(s * norm.cdf(d1) - k * math.exp(-r * t) * norm.cdf(d2))


def merton_exact_call(
    params: MertonParams,
    strike: float | None = None,
    n_terms: int = 150,
) -> float:
    """Return Merton's Poisson-weighted Black-Scholes call price.

    C = sum_n Pois(n; lambda'*T) * BS(S, K, T, r_n, sigma_n)

    where r_n and sigma_n are obtained by conditioning on n jumps.
    Log-weights are used for numerical stability at large lambda*T.
    """
    k = params.strike if strike is None else strike
    t = params.maturity
    lam_t = params.lam_prime * t
    price = 0.0

    for n in range(n_terms):
        if lam_t > 0.0:
            log_weight = -lam_t + n * math.log(lam_t) - math.lgamma(n + 1)
            weight = math.exp(log_weight)
        else:
            weight = 1.0 if n == 0 else 0.0

        if n > 5 and weight < 1e-16:
            break

        r_n = (
            params.rate
            - params.lam * params.kappa
            + n * params.mu_j / t
            + n * params.sigma_j ** 2 / (2.0 * t)
        )
        sigma_n = math.sqrt(params.sigma ** 2 + n * params.sigma_j ** 2 / t)
        price += weight * black_scholes_call(params.s0, k, t, r_n, sigma_n)

    return float(price)


def implied_volatility(price: float, s: float, k: float, t: float, r: float) -> float:
    """Invert a call price to Black-Scholes implied volatility via Brent's method."""
    lower_bound = max(s - k * math.exp(-r * t), 0.0)
    if price < lower_bound - 1e-10:
        return float("nan")

    def objective(vol: float) -> float:
        return black_scholes_call(s, k, t, r, vol) - price

    try:
        return float(brentq(objective, 1e-6, 5.0, xtol=1e-10, maxiter=200))
    except ValueError:
        return float("nan")


# ── simulation ───────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class PriceResult:
    """Monte Carlo price estimate and standard error."""
    price: float
    standard_error: float


@dataclass(frozen=True)
class McSample:
    """Terminal prices generated by the simulation engine."""
    terminal_prices: np.ndarray
    control_prices: np.ndarray | None = None
    antithetic_half_size: int | None = None


def _simulate_jump_sums(
    rng: np.random.Generator,
    jump_counts: np.ndarray,
    mu_j: float,
    sigma_j: float,
) -> np.ndarray:
    """Vectorized compound-normal jump sums conditional on Poisson counts."""
    jump_sums = np.zeros_like(jump_counts, dtype=float)
    active = jump_counts > 0
    if np.any(active):
        counts = jump_counts[active]
        jump_sums[active] = rng.normal(
            loc=counts * mu_j,
            scale=np.sqrt(counts) * sigma_j,
            size=counts.size,
        )
    return jump_sums


def simulate_terminal_prices(
    params: MertonParams,
    paths: int,
    seed: int,
    *,
    antithetic: bool = False,
    moment_match: bool = False,
    include_control: bool = False,
) -> McSample:
    """Simulate terminal prices under the exact Merton terminal distribution.

    Antithetic variates pair (+Z, -Z) Brownian shocks with independent jump
    components to preserve the negative correlation that drives variance
    reduction without eliminating the diffusion channel.
    """
    if paths <= 0:
        raise ValueError("paths must be positive")

    rng = np.random.default_rng(seed)
    p = params
    t = p.maturity
    drift_merton = (p.rate - p.lam * p.kappa - 0.5 * p.sigma ** 2) * t
    drift_gbm = (p.rate - 0.5 * p.sigma ** 2) * t
    diffusion_scale = p.sigma * math.sqrt(t)

    antithetic_half_size: int | None = None
    if antithetic:
        half = max(paths // 2, 1)
        z_half = rng.standard_normal(half)
        z = np.concatenate([z_half, -z_half])
        jump_counts_pos = rng.poisson(p.lam * t, size=half)
        jump_counts_neg = rng.poisson(p.lam * t, size=half)
        jump_sums = np.concatenate([
            _simulate_jump_sums(rng, jump_counts_pos, p.mu_j, p.sigma_j),
            _simulate_jump_sums(rng, jump_counts_neg, p.mu_j, p.sigma_j),
        ])
        antithetic_half_size = half
    else:
        z = rng.standard_normal(paths)
        jump_counts = rng.poisson(p.lam * t, size=paths)
        jump_sums = _simulate_jump_sums(rng, jump_counts, p.mu_j, p.sigma_j)

    log_terminal = math.log(p.s0) + drift_merton + diffusion_scale * z + jump_sums
    terminal_prices = np.exp(log_terminal)

    if moment_match:
        expected_terminal = p.s0 * math.exp(p.rate * t)
        sample_mean = float(terminal_prices.mean())
        if sample_mean <= 0.0:
            raise RuntimeError("moment matching failed: non-positive terminal-price mean")
        terminal_prices *= expected_terminal / sample_mean

    control_prices = None
    if include_control:
        control_prices = np.exp(math.log(p.s0) + drift_gbm + diffusion_scale * z)

    return McSample(
        terminal_prices=terminal_prices,
        control_prices=control_prices,
        antithetic_half_size=antithetic_half_size,
    )


def simulate_terminal_prices_grid(
    params: MertonParams,
    paths: int,
    steps: int,
    seed: int,
) -> np.ndarray:
    """Simulate terminal prices step-by-step for time-grid stability diagnostics."""
    if paths <= 0:
        raise ValueError("paths must be positive")
    if steps <= 0:
        raise ValueError("steps must be positive")

    rng = np.random.default_rng(seed)
    p = params
    dt = p.maturity / steps
    drift = (p.rate - p.lam * p.kappa - 0.5 * p.sigma ** 2) * dt
    diffusion_scale = p.sigma * math.sqrt(dt)
    log_s = np.full(paths, math.log(p.s0), dtype=float)

    for _ in range(steps):
        z = rng.standard_normal(paths)
        jump_counts = rng.poisson(p.lam * dt, size=paths)
        jump_sums = _simulate_jump_sums(rng, jump_counts, p.mu_j, p.sigma_j)
        log_s += drift + diffusion_scale * z + jump_sums

    return np.exp(log_s)


def _price_from_discounted_payoffs(
    discounted_payoffs: np.ndarray,
    antithetic_half_size: int | None = None,
) -> PriceResult:
    """Compute mean price and standard error from discounted payoffs."""
    if antithetic_half_size is not None:
        half = antithetic_half_size
        pair_means = 0.5 * (discounted_payoffs[:half] + discounted_payoffs[half: 2 * half])
        return PriceResult(
            price=float(pair_means.mean()),
            standard_error=float(pair_means.std(ddof=1) / math.sqrt(pair_means.size)),
        )
    return PriceResult(
        price=float(discounted_payoffs.mean()),
        standard_error=float(discounted_payoffs.std(ddof=1) / math.sqrt(discounted_payoffs.size)),
    )


def price_from_terminal(
    terminal_prices: np.ndarray,
    params: MertonParams,
    strike: float | None = None,
) -> PriceResult:
    """Price a European call from pre-simulated terminal prices."""
    k = params.strike if strike is None else strike
    discounted = math.exp(-params.rate * params.maturity) * np.maximum(terminal_prices - k, 0.0)
    return _price_from_discounted_payoffs(discounted)


def merton_mc_call(
    params: MertonParams,
    config: RunConfig,
    *,
    antithetic: bool = False,
    moment_match: bool = False,
    control_variate: bool = False,
) -> PriceResult:
    """Estimate the Merton European call price by Monte Carlo."""
    sample = simulate_terminal_prices(
        params,
        paths=config.paths,
        seed=config.seed,
        antithetic=antithetic,
        moment_match=moment_match,
        include_control=control_variate,
    )

    if control_variate:
        if sample.control_prices is None:
            raise RuntimeError("control prices were not simulated")

        raw_payoffs = np.maximum(sample.terminal_prices - params.strike, 0.0)
        control_payoffs = np.maximum(sample.control_prices - params.strike, 0.0)
        control_exact_undiscounted = math.exp(params.rate * params.maturity) * black_scholes_call(
            params.s0, params.strike, params.maturity, params.rate, params.sigma,
        )
        control_var = float(np.var(control_payoffs, ddof=1))
        beta = 0.0 if control_var <= 0.0 else float(
            np.cov(raw_payoffs, control_payoffs, ddof=1)[0, 1] / control_var
        )
        adjusted = raw_payoffs - beta * (control_payoffs - control_exact_undiscounted)
        discounted = math.exp(-params.rate * params.maturity) * adjusted
        return _price_from_discounted_payoffs(discounted, sample.antithetic_half_size)

    discounted = math.exp(-params.rate * params.maturity) * np.maximum(
        sample.terminal_prices - params.strike, 0.0
    )
    return _price_from_discounted_payoffs(discounted, sample.antithetic_half_size)


# ── experiment builders ───────────────────────────────────────────────────────

@dataclass(frozen=True)
class SmileScenario:
    """Named parameter overrides for the implied-vol smile comparison."""
    label: str
    overrides: dict[str, float] = field(default_factory=dict)


def build_validation_table(params: MertonParams, config: RunConfig) -> pd.DataFrame:
    """Compare the Merton analytic price to the plain MC estimate."""
    exact = merton_exact_call(params, n_terms=config.merton_terms)
    mc = merton_mc_call(params, config)
    return pd.DataFrame([
        {"method": "Merton exact", "price": exact, "standard_error": 0.0, "absolute_error": 0.0},
        {
            "method": "Monte Carlo",
            "price": mc.price,
            "standard_error": mc.standard_error,
            "absolute_error": abs(mc.price - exact),
        },
    ])


def build_variance_reduction_table(params: MertonParams, config: RunConfig) -> pd.DataFrame:
    """Evaluate variance-reduction methods against the Merton exact price.

    The variance_reduction_factor column reports (SE_plain / SE_method)^2;
    values above 1 indicate effective variance reduction.
    """
    exact = merton_exact_call(params, n_terms=config.merton_terms)
    methods: Sequence[tuple[str, dict[str, bool]]] = [
        ("plain", {}),
        ("antithetic", {"antithetic": True}),
        ("moment_matching", {"moment_match": True}),
        ("control_variate", {"control_variate": True}),
        ("antithetic_moment_matching", {"antithetic": True, "moment_match": True}),
        ("antithetic_control_variate", {"antithetic": True, "control_variate": True}),
    ]

    rows: list[dict] = []
    plain_se: float | None = None
    for name, kwargs in methods:
        result = merton_mc_call(params, config, **kwargs)
        if name == "plain":
            plain_se = result.standard_error
        se_ratio = (result.standard_error / plain_se) if plain_se else 1.0
        vr_factor = (1.0 / se_ratio) ** 2 if se_ratio > 0.0 else float("nan")
        rows.append({
            "method": name,
            "price": result.price,
            "standard_error": result.standard_error,
            "absolute_error": abs(result.price - exact),
            "se_ratio_vs_plain": se_ratio,
            "variance_reduction_factor": vr_factor,
        })

    return pd.DataFrame(rows)


def build_sensitivity_table(params: MertonParams, config: RunConfig) -> pd.DataFrame:
    """Report control-variate efficiency across a range of jump-vol regimes."""
    jump_vol_grid = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30]
    rows: list[dict] = []
    for sigma_j in jump_vol_grid:
        p = params.replace(sigma_j=sigma_j)
        plain = merton_mc_call(p, config)
        cv = merton_mc_call(p, config, control_variate=True)
        se_ratio = cv.standard_error / plain.standard_error if plain.standard_error > 0.0 else float("nan")
        vr_factor = (1.0 / se_ratio) ** 2 if se_ratio and se_ratio > 0.0 else float("nan")
        rows.append({
            "jump_vol": sigma_j,
            "plain_standard_error": plain.standard_error,
            "control_standard_error": cv.standard_error,
            "variance_reduction_factor": vr_factor,
        })
    return pd.DataFrame(rows)


def run_convergence_study(
    params: MertonParams,
    config: RunConfig,
    path_sizes: Iterable[int],
) -> pd.DataFrame:
    """RMSE convergence study varying the number of Monte Carlo paths."""
    exact = merton_exact_call(params, n_terms=config.merton_terms)
    rows: list[dict] = []

    for paths in path_sizes:
        estimates = []
        for rep in range(config.replications):
            run_cfg = RunConfig(
                paths=paths, steps=config.steps, seed=config.seed + rep,
                replications=config.replications, merton_terms=config.merton_terms,
                cos_n=config.cos_n, cos_l=config.cos_l, output_dir=config.output_dir,
            )
            estimates.append(merton_mc_call(params, run_cfg).price)
        arr = np.asarray(estimates)
        rows.append({
            "paths": paths,
            "mean_price": float(arr.mean()),
            "rmse": float(np.sqrt(np.mean((arr - exact) ** 2))),
        })

    return pd.DataFrame(rows)


def run_time_grid_stability(
    params: MertonParams,
    config: RunConfig,
    step_sizes: Iterable[int],
) -> pd.DataFrame:
    """Check numerical stability across time-grid refinements."""
    exact = merton_exact_call(params, n_terms=config.merton_terms)
    rows: list[dict] = []

    for steps in step_sizes:
        estimates = []
        for rep in range(config.replications):
            terminal = simulate_terminal_prices_grid(
                params, paths=config.paths, steps=steps, seed=config.seed + rep,
            )
            estimates.append(price_from_terminal(terminal, params).price)
        arr = np.asarray(estimates)
        rows.append({
            "steps": steps,
            "mean_price": float(arr.mean()),
            "rmse": float(np.sqrt(np.mean((arr - exact) ** 2))),
        })

    return pd.DataFrame(rows)


def build_smile_table(
    params: MertonParams,
    strikes: Iterable[float],
    n_terms: int,
    scenarios: Sequence[SmileScenario] | None = None,
) -> pd.DataFrame:
    """Compute implied vols across strikes for GBM, Merton baseline, and large-jump scenarios."""
    if scenarios is None:
        scenarios = (
            SmileScenario(label="gbm", overrides={"lam": 0.0}),
            SmileScenario(label="merton_baseline", overrides={}),
            SmileScenario(label="merton_large_negative_jumps", overrides={"mu_j": -0.20}),
        )

    strike_list = list(strikes)
    rows: list[dict] = []
    for scenario in scenarios:
        p = params.replace(**scenario.overrides)
        for k in strike_list:
            price = merton_exact_call(p, strike=k, n_terms=n_terms)
            iv = implied_volatility(price, p.s0, k, p.maturity, p.rate)
            rows.append({
                "scenario": scenario.label,
                "strike": k,
                "moneyness": k / p.s0,
                "model_price": price,
                "implied_vol": iv,
            })

    return pd.DataFrame(rows)


# ── plot renderers ────────────────────────────────────────────────────────────

def save_convergence_plot(
    convergence: pd.DataFrame,
    stability: pd.DataFrame,
    output_path: Path,
) -> None:
    """Save convergence and time-grid stability diagnostics as a PDF figure."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))

    axes[0].loglog(convergence["paths"], convergence["rmse"], marker="o", label="MC RMSE")
    reference = (
        convergence["rmse"].iloc[0]
        * math.sqrt(convergence["paths"].iloc[0])
        / np.sqrt(convergence["paths"].to_numpy())
    )
    axes[0].loglog(convergence["paths"], reference, linestyle="--", label=r"$1/\sqrt{N}$ reference")
    axes[0].set_title("Convergence in Number of Paths")
    axes[0].set_xlabel("Number of paths")
    axes[0].set_ylabel("RMSE")
    axes[0].grid(alpha=0.3, which="both")
    axes[0].legend()

    axes[1].loglog(stability["steps"], stability["rmse"], marker="s")
    axes[1].set_title("Time-Grid Stability")
    axes[1].set_xlabel("Number of time steps")
    axes[1].set_ylabel("RMSE")
    axes[1].grid(alpha=0.3, which="both")

    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def save_smile_plot(smile: pd.DataFrame, output_path: Path) -> None:
    """Save the implied-volatility smile comparison as a PDF figure."""
    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    styles = {
        "gbm": {"linestyle": "--", "marker": "x", "label": r"GBM ($\lambda = 0$)"},
        "merton_baseline": {"marker": "o", "label": "Merton baseline"},
        "merton_large_negative_jumps": {"marker": "s", "label": r"Merton, $\mu_J = -0.20$"},
    }
    for name, group in smile.groupby("scenario"):
        style = styles.get(str(name), {"marker": "o", "label": str(name)})
        ax.plot(group["moneyness"], group["implied_vol"], **style)

    ax.set_title("Implied Volatility Smile")
    ax.set_xlabel("Moneyness K/S0")
    ax.set_ylabel("Implied volatility")
    ax.grid(alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


def save_sensitivity_plot(sensitivity: pd.DataFrame, output_path: Path) -> None:
    """Save the control-variate efficiency vs jump-vol dispersion as a PDF figure."""
    fig, ax = plt.subplots(figsize=(7.0, 4.5))
    ax.plot(sensitivity["jump_vol"], sensitivity["variance_reduction_factor"], marker="o")
    ax.axhline(1.0, linestyle=":", linewidth=0.8)
    ax.set_title("Control-Variate Efficiency vs Jump-Size Dispersion")
    ax.set_xlabel(r"Jump volatility $\sigma_J$")
    ax.set_ylabel("Variance reduction factor")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_path)
    plt.close(fig)


# ── pipeline entry point ──────────────────────────────────────────────────────

def write_outputs(
    params: MertonParams,
    config: RunConfig,
    path_sizes: list[int] | None = None,
    step_sizes: list[int] | None = None,
    strikes: list[float] | None = None,
) -> None:
    """Run the full W3 Monte Carlo pipeline and write CSV/PDF outputs.

    Parameters
    ----------
    params:
        Merton model parameters (read from .env via load_config()).
    config:
        Runtime settings including output directory.
    path_sizes:
        Path counts for the convergence study.
    step_sizes:
        Time-step counts for the stability study.
    strikes:
        Strike prices for the implied-vol smile.
    """
    if path_sizes is None:
        path_sizes = [1_000, 5_000, 10_000, 25_000, 50_000]
    if step_sizes is None:
        step_sizes = [1, 12, 52, 252]
    if strikes is None:
        strikes = [70.0, 80.0, 90.0, 100.0, 110.0, 120.0, 130.0]

    out = config.output_dir / "w3"
    out.mkdir(parents=True, exist_ok=True)
    LOGGER.info("Writing W3 outputs to %s", out)

    validation = build_validation_table(params, config)
    variance = build_variance_reduction_table(params, config)
    sensitivity = build_sensitivity_table(params, config)
    convergence = run_convergence_study(params, config, path_sizes)
    stability = run_time_grid_stability(params, config, step_sizes)
    smile = build_smile_table(params, strikes, config.merton_terms)

    validation.to_csv(out / "validation_summary.csv", index=False)
    variance.to_csv(out / "variance_reduction_table.csv", index=False)
    sensitivity.to_csv(out / "control_variate_sensitivity.csv", index=False)
    convergence.to_csv(out / "path_convergence.csv", index=False)
    stability.to_csv(out / "time_grid_stability.csv", index=False)
    smile.to_csv(out / "implied_vol_smile.csv", index=False)

    save_convergence_plot(convergence, stability, out / "convergence_study.pdf")
    save_smile_plot(smile, out / "implied_vol_smile.pdf")
    save_sensitivity_plot(sensitivity, out / "control_variate_sensitivity.pdf")

    LOGGER.info("Validation:\n%s", validation.to_string(index=False))
    LOGGER.info("Variance reduction:\n%s", variance.to_string(index=False))
    LOGGER.info("W3 complete — outputs in %s", out)
