"""Monte Carlo simulation engine for the Merton jump-diffusion model.

The pricing kernel separates the simulation of terminal prices from the
discounting step.  This keeps the variance-reduction logic local to the
estimator, while leaving the underlying paths reusable for diagnostics such
as time-grid stability checks.

The Brownian shocks and Poisson jump components are sampled in a way that is
consistent with the W2 SDE:

    dX_t = (r - lambda * kappa - 0.5 * sigma**2) dt + sigma dW_t + J dN_t,
    kappa = E[exp(J)-1] = exp(mu_J + 0.5 * sigma_J**2) - 1.

Antithetic variates pair (+Z, -Z) Brownian shocks while drawing the jump
component independently for the two branches: the diffusion channel still
provides the negative pair correlation that drives the variance reduction,
whereas sharing the jump realisation across the pair eliminates it and can
inflate the pair-mean variance instead.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np

from config import MarketParams, RunConfig
from pricing import black_scholes_call


@dataclass(frozen=True)
class PriceResult:
    """Monte Carlo price estimate and standard error."""

    price: float
    standard_error: float


@dataclass(frozen=True)
class McSample:
    """Terminal prices generated by the simulation engine."""

    terminal_prices: np.ndarray
    control_prices: np.ndarray | None = None
    antithetic_half_size: int | None = None


def _simulate_jump_sums(
    rng: np.random.Generator,
    jump_counts: np.ndarray,
    jump_mean: float,
    jump_vol: float,
) -> np.ndarray:
    """Simulate compound-normal jump sums conditional on Poisson counts.

    Conditional on N=n, the jump sum is N(n*mu_J, n*sigma_J^2).  This avoids a
    slow inner loop over paths and keeps the implementation vectorized.
    """
    jump_sums = np.zeros_like(jump_counts, dtype=float)
    active = jump_counts > 0
    if np.any(active):
        counts = jump_counts[active]
        jump_sums[active] = rng.normal(
            loc=counts * jump_mean,
            scale=np.sqrt(counts) * jump_vol,
            size=counts.size,
        )
    return jump_sums


def simulate_terminal_prices(
    params: MarketParams,
    paths: int,
    seed: int,
    *,
    antithetic: bool = False,
    moment_match: bool = False,
    include_control: bool = False,
) -> McSample:
    """Simulate terminal prices under the exact Merton terminal distribution.

    Brownian shocks are paired as (+Z, -Z) when antithetic variates are enabled.
    The jump component is drawn independently for the positive and negative
    branches so that the conditional correlation between paired payoffs is
    driven by the diffusion channel alone; sharing the same jump realisation
    across the pair eliminates that channel and can inflate the variance of
    the pair-mean estimator.  The optional GBM control variate reuses the
    Merton Brownian shocks, which is required for the control payoff to be
    strongly correlated with the target payoff.
    """
    if paths <= 0:
        raise ValueError("paths must be positive")

    rng = np.random.default_rng(seed)
    p = params
    t = p.maturity
    drift_merton = (p.rate - p.jump_intensity * p.kappa - 0.5 * p.sigma**2) * t
    drift_gbm = (p.rate - 0.5 * p.sigma**2) * t
    diffusion_scale = p.sigma * math.sqrt(t)

    antithetic_half_size: int | None = None
    if antithetic:
        half = max(paths // 2, 1)
        z_half = rng.standard_normal(half)
        z = np.concatenate([z_half, -z_half])

        jump_counts_pos = rng.poisson(p.jump_intensity * t, size=half)
        jump_counts_neg = rng.poisson(p.jump_intensity * t, size=half)
        jump_sums_pos = _simulate_jump_sums(rng, jump_counts_pos, p.jump_mean, p.jump_vol)
        jump_sums_neg = _simulate_jump_sums(rng, jump_counts_neg, p.jump_mean, p.jump_vol)
        jump_sums = np.concatenate([jump_sums_pos, jump_sums_neg])
        antithetic_half_size = half
    else:
        z = rng.standard_normal(paths)
        jump_counts = rng.poisson(p.jump_intensity * t, size=paths)
        jump_sums = _simulate_jump_sums(rng, jump_counts, p.jump_mean, p.jump_vol)

    log_terminal = math.log(p.s0) + drift_merton + diffusion_scale * z + jump_sums
    terminal_prices = np.exp(log_terminal)

    if moment_match:
        expected_terminal = p.s0 * math.exp(p.rate * t)
        sample_mean = float(terminal_prices.mean())
        if sample_mean <= 0.0:
            raise RuntimeError("moment matching failed: non-positive terminal-price mean")
        terminal_prices *= expected_terminal / sample_mean

    control_prices = None
    if include_control:
        control_prices = np.exp(math.log(p.s0) + drift_gbm + diffusion_scale * z)

    return McSample(
        terminal_prices=terminal_prices,
        control_prices=control_prices,
        antithetic_half_size=antithetic_half_size,
    )


def simulate_terminal_prices_grid(
    params: MarketParams,
    paths: int,
    steps: int,
    seed: int,
) -> np.ndarray:
    """Simulate terminal prices on a time grid for stability diagnostics."""
    if paths <= 0:
        raise ValueError("paths must be positive")
    if steps <= 0:
        raise ValueError("steps must be positive")

    rng = np.random.default_rng(seed)
    p = params
    dt = p.maturity / steps
    drift = (p.rate - p.jump_intensity * p.kappa - 0.5 * p.sigma**2) * dt
    diffusion_scale = p.sigma * math.sqrt(dt)
    log_s = np.full(paths, math.log(p.s0), dtype=float)

    for _ in range(steps):
        z = rng.standard_normal(paths)
        jump_counts = rng.poisson(p.jump_intensity * dt, size=paths)
        jump_sums = _simulate_jump_sums(rng, jump_counts, p.jump_mean, p.jump_vol)
        log_s += drift + diffusion_scale * z + jump_sums

    return np.exp(log_s)


def _price_from_discounted_payoffs(
    discounted_payoffs: np.ndarray,
    antithetic_half_size: int | None = None,
) -> PriceResult:
    """Return mean price and standard error from discounted payoffs.

    For antithetic samples the standard error is computed from pair means since
    payoffs within an antithetic pair are not independent draws.
    """
    if antithetic_half_size is not None:
        half = antithetic_half_size
        pair_means = 0.5 * (discounted_payoffs[:half] + discounted_payoffs[half : 2 * half])
        return PriceResult(
            price=float(pair_means.mean()),
            standard_error=float(pair_means.std(ddof=1) / math.sqrt(pair_means.size)),
        )

    return PriceResult(
        price=float(discounted_payoffs.mean()),
        standard_error=float(discounted_payoffs.std(ddof=1) / math.sqrt(discounted_payoffs.size)),
    )


def price_from_terminal(
    terminal_prices: np.ndarray,
    params: MarketParams,
    strike: float | None = None,
) -> PriceResult:
    """Price a European call from simulated terminal prices."""
    k = params.strike if strike is None else strike
    discounted_payoffs = math.exp(-params.rate * params.maturity) * np.maximum(
        terminal_prices - k,
        0.0,
    )
    return _price_from_discounted_payoffs(discounted_payoffs)


def merton_mc_call(
    params: MarketParams,
    config: RunConfig,
    *,
    antithetic: bool = False,
    moment_match: bool = False,
    control_variate: bool = False,
) -> PriceResult:
    """Estimate the Merton European call price by Monte Carlo."""
    sample = simulate_terminal_prices(
        params,
        paths=config.paths,
        seed=config.seed,
        antithetic=antithetic,
        moment_match=moment_match,
        include_control=control_variate,
    )

    if control_variate:
        if sample.control_prices is None:
            raise RuntimeError("control variate requested but control prices were not simulated")

        raw_payoffs = np.maximum(sample.terminal_prices - params.strike, 0.0)
        control_payoffs = np.maximum(sample.control_prices - params.strike, 0.0)
        control_exact_undiscounted_mean = math.exp(params.rate * params.maturity) * black_scholes_call(
            params.s0,
            params.strike,
            params.maturity,
            params.rate,
            params.sigma,
        )

        control_var = float(np.var(control_payoffs, ddof=1))
        beta = 0.0 if control_var <= 0.0 else float(np.cov(raw_payoffs, control_payoffs, ddof=1)[0, 1] / control_var)
        adjusted_payoffs = raw_payoffs - beta * (control_payoffs - control_exact_undiscounted_mean)
        discounted = math.exp(-params.rate * params.maturity) * adjusted_payoffs
        return _price_from_discounted_payoffs(discounted, sample.antithetic_half_size)

    discounted = math.exp(-params.rate * params.maturity) * np.maximum(
        sample.terminal_prices - params.strike,
        0.0,
    )
    return _price_from_discounted_payoffs(discounted, sample.antithetic_half_size)
